### ISSUE TITLE
Add hashing to passwords 

### ISSUE THREAD

**Issue by annu12340** [annu12340/Choose-Smart#3]
As of now, the passwords are directly saved into the db. However, this is insecure
Use the hash() in python to hash the passwords and then save it to the db

**Comment by kavya1229** [comment]
can I work on this?

**Comment by annu12340** [comment]
Yeah sure :)

**Comment by kavya1229** [comment]
@annu12340 can you please provide the requirements.txt file.

**Comment by annu12340** [comment]
Solved
